language: python

python:
  - "2.7"

env:
  - DJANGO_PACKAGE="django>=1.6,<1.7"
  - DJANGO_PACKAGE="django>=1.7,<1.8"

matrix:
  # Include specific versions Django for Python 3
  include:
  - python: "3.3"
    env: DJANGO_PACKAGE="django>=1.6,<1.7"
  - python: "3.4"
    env: DJANGO_PACKAGE="django>=1.6,<1.7"
    env: DJANGO_PACKAGE="django>=1.7,<1.8"
  - python: "3.5-dev"
    env: DJANGO_PACKAGE="django>=1.6,<1.7"
    env: DJANGO_PACKAGE="django>=1.7,<1.8"
  allow_failures:
    - python: "3.5-dev"

install:
  - pip install -q $DJANGO_PACKAGE six https://github.com/python-odin/odin/archive/master.zip
  - pip install coveralls

script: coverage run django_test_runner/__main__.py baldr

after_success:
  - coveralls
