language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_PACKAGE="django>=1.6,<1.7"
  - DJANGO_PACKAGE="django>=1.7,<1.8"
  - DJANGO_PACKAGE="django>=1.8,<1.9"

matrix:
  allow_failures:
    - python: "3.5"

install:
  - pip install -q $DJANGO_PACKAGE six https://github.com/python-odin/odin/archive/master.zip
  - pip install coveralls

script: coverage run django_test_runner/__main__.py baldr

after_success:
  - coveralls
