language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO=django>=1.9,<1.10
  - DJANGO=django>=1.8,<1.9
  - DJANGO=django>=1.7,<1.8
  - DJANGO=django>=1.6,<1.7

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=django>=1.7,<1.8
    - python: "3.5"
      env: DJANGO=django>=1.6,<1.7

install:
  - pip install -q $DJANGO_PACKAGE six https://github.com/python-odin/odin/archive/master.zip
  - pip install coveralls

script: coverage run django_test_runner/__main__.py baldr

after_success:
  - coveralls
