language: python

python:
  - "2.7"

env:
  - DJANGO_PACKAGE="django>=1.6,<1.7"
  - DJANGO_PACKAGE="https://www.djangoproject.com/download/1.7c2/tarball/"

matrix:
  # Release candiate status
  allow_failures:
  - env: DJANGO_PACKAGE="https://www.djangoproject.com/download/1.7c2/tarball/"

  # Include specific versions Django for Python 3
  include:
  - python: "3.3"
    env: DJANGO_PACKAGE="django>=1.6,<1.7"
  - python: "3.4"
    env: DJANGO_PACKAGE="django>=1.6,<1.7"
  - python: "3.4"
    env: DJANGO_PACKAGE="https://www.djangoproject.com/download/1.7c2/tarball/"

install:
  - pip install -q $DJANGO_PACKAGE six -egit+https@github.com:timsavage/odin.git#egg=Odin
  - pip install coveralls

script: coverage run django_test_runner/__main__.py baldr

after_success:
  - coveralls
